### ISSUE TITLE
BUG: Client crash when joining

### ISSUE THREAD

**Issue by sogata-aw** [DiffuseHyperion/InertiaAntiCheat#14]
**Describe the bug**
I've tried to log in my server but before sending my mod list it crash
**To Reproduce**
Steps to reproduce the problem:
1. Enable option '...'
2. Join the server with '...'
3. See error

**Expected behavior**

**Screenshots**
When I crash I got this error:
java.lang.NoSuchMethodError: 'void net.minecraft.class_634.method_52787(net.minecraft.class_2596)'
	at me.diffusehyperion.inertiaanticheat.packets.ModListRequestS2CPacket.lambda$receive$0(ModListRequestS2CPacket.java:63)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Server information (please complete the following information):**
 - Server software: Fabric
 - Server software loader version: 0.14.25
 - Minecraft version: 1.20.1
 - Mod version: 0.0.6.2
 - Fabric API version: 0.91.0+1.20.1

**Mod config**
```
Paste your server's InertiaAntiCheat.toml file contents here! 
# Time to wait for the client to send back their mod list before kicking them.
# If the delay is too short, clients may not have enough time to send their response, depending on their internet.
# If the delay is too long, clients may hang around for too long.
# The player's movement, actions and chat messages are frozen at this time.
[grace]
graceTime = 3000
# The reason for kicking a player due to them not responding to the server's request.
disconnectMessage = "You were kicked for not sending a response to the anticheat!\nThis is probably due to missing the anticheat client mod.\nInstall it here: https://modrinth.com/mod/inertiaanticheat"
# Title text to show when the player is frozen. (when the server is waiting for a response from the player)
# Make this empty to disable showing titles.
titleText = "Please wait..."
# Make this empty to disable showing subtitles.
subtitleText = "The server is checking your mods..."

[mods]
# Shw the mod list of everybody who joins.
# Useful for discovering the true mod name of the mods you want to target!
showMods = true

# Immediately kick players who have these mods in their modlist.
# The mod checks (and kicks) for blacklisted mods first.
# Enabling debug will show the full modlist of players joining, allowing you to discover mod names.
blacklist = ["Wurst Client", "Meteor Client"]
# The reason for kicking a player due to having blacklisted mods installed.
# Use ${blacklisted} as a placeholder for all blacklisted mods found on the player.
blacklistMessage = "You were kicked for having illegal mods installed!\nRemove ${blacklisted} before rejoining the server."

# Immediately kick players who do not have these mods in their modlist.
# Enabling debug will show the full modlist of players joining, allowing you to discover mod names.
whitelist = []
# The reason for kicking a player due to not having whitelisted mods installed.
# Use ${whitelisted} as a placeholder for all whitelisted mods not found on the player.
whitelistMessage = "You were kicked for having not having required mods installed!\nInstall ${whitelisted} before rejoining the server."

[hash]
# Alternatively, the server can create a MD5 hash of their modlist, and match it against this.
# This is recommended for modpacks.

# Show each connecting player's modlist hash in your server logs. Useful to find out your modpack's hash.
showHash = true

# The hash for the server to check against. See "showHash" for more details.
# Filling this will cause the server to disreguard blacklisted/whitelisted mods.
# Soft whitelisted mods (see below) will still be checked.
# You can add multiple hashes into the list, and the server will check against all of them.
hash = []
# What hashing algorithm to use when creating the hash.
# Accepted values: "MD5", "SHA-1", "SHA-256"
algorithm = "MD5"
# The reason for kicking a player due to their modlist hash not matching up.
hashMessage = "You were kicked for not matching the server's modlist!\nDid you install their modpack correctly?"

# Allow certain mods to be used by players, in addition to your modpack.
# This allows players to make use of optional client mods if you allow it.
softWhitelist = []

[e2ee]
# Enable using end-to-end encryption to encrypt modlists coming from clients.
# This prevents outside sources from reading and modifying modlists coming from clients.
# This doesn't prevent clients from modfiying their own modlists though.
enable = false

# Name of the private and public key files to use for E2EE.
# DO NOT LEAK YOUR PRIVATE KEY!
privateKeyName = "private.key"
publicKeyName = "public.key"

# The reason for kicking a player due to them disabling support for E2EE.
unsupportedMessage = "The server is using E2EE, but you have disabled support for E2EE!\nPlease look in your config file for more information."

[debug]
# Show additional information in server logs.
debug = true
# do not touch pls :)
version = 4


**Additional context**
Add any other context about the problem here.
Here would also be the place where you put any other mods you were running when the problem occured.

**Comment by sogata-aw** [comment]
Just a little update, It's only on the 0.0.6.2 that it crash, I tried it with 0.0.6.1 and it works

**Comment by DiffuseHyperion** [comment]
Hi sorry for the late reply. I'm unable to work on this project atm, will look into this when I can. Thanks for reporting the bug :)

**Comment by sogata-aw** [comment]
You welcome :)

**Comment by DiffuseHyperion** [comment]
Closing this for now as this is on the alpha versions
