### ISSUE TITLE
BUG: Crashes 

### ISSUE THREAD

**Issue by Mrgaton** [DiffuseHyperion/InertiaAntiCheat#25]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-03-17 11:27:10
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.class_634.method_52787(net.minecraft.class_2596)'
	at me.diffusehyperion.inertiaanticheat.packets.ModListRequestS2CPacket.lambda$receive$0(ModListRequestS2CPacket.java:63)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.diffusehyperion.inertiaanticheat.packets.ModListRequestS2CPacket.lambda$receive$0(ModListRequestS2CPacket.java:63)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)

-- Affected level --
Details:
	All players: 1 total; [class_746['Mrgaton'/215, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 262144, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1 game time, 1 day time
	Server brand: ~~NULL~~
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Round-Trees-7.1-1.19+.zip, file/Dramatic Skys Beta 2.2.zip, file/FreshAnimations_v1.9.zip, file/Alacrity.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1849178280 bytes (1763 MiB) / 2969567232 bytes (2832 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f15
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5176
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=27.20.100.9365
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 25901.36
	Virtual memory used (MB): 18514.60
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 345.05
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx12288m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		appleskin: AppleSkin 2.5.1+mc1.20
		autohud: Auto HUD 6.3.3+1.20.1
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		betterend: Better End 4.0.11
		betternether: Better Nether 9.0.10
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		comforts: Comforts 6.3.5+1.20.1
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
			spectrelib: SpectreLib 0.13.15+1.20.1
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
		croptopia: Croptopia 3.0.3
		distanthorizons: Distant Horizons 2.0.2-a-dev
		dynamiccrosshair: Dynamic Crosshair 7.4.4+1.20
			yaclx: YetAnotherConfigLibExtensions 1.12+1.20.2
		eatinganimationid: Eating Animation 1.20+1.9.5
		epherolib: EpheroLib 1.2.0
		fabric-api: Fabric API 0.92.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.4+1802ada577
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fabricskyboxes: FabricSkyBoxes 0.7.3+mc1.20.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		geckolib: GeckoLib 4 4.4.2
			com_eliotlash_mclib_mclib: mclib 20
		iceberg: Iceberg 1.1.18
		indium: Indium 1.0.30+mc1.20.4
		inertiaanticheat: InertiaAntiCheat 0.0.6.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		iris: Iris 1.7-alpha.1-185a9812
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		legendarytooltips: Legendary Tooltips 1.4.5
		lithium: Lithium 0.11.2
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.1
		naturalist: Naturalist 4.0.3
		presencefootsteps: Presence Footsteps 1.9.2
			kirin: Kirin UI 1.15.4+1.20
		prism: Prism 1.0.5
		skinlayers3d: 3d-Skin-Layers 1.6.2
		sodium: Sodium 0.5.8+mc1.20.1
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.3.1
		voicechat: Simple Voice Chat 1.20.1-2.5.8
	Loaded Shaderpack: Bliss-Shader-main.zip
		Profile: Custom (+0 options changed by user)
	Launched Version: fabric-loader-0.15.7-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.76, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Round-Trees-7.1-1.19+.zip (incompatible), file/Dramatic Skys Beta 2.2.zip, file/FreshAnimations_v1.9.zip, file/Alacrity.zip
	Current Language: es_es
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

**Comment by FauxStar** [comment]
same problem here

**Comment by DiffuseHyperion** [comment]
Seen this yesterday, need some time to fix this since school just started again lol

**Comment by Mrgaton** [comment]
Happends just when I join the server also is a bit confusing how I have to put the yes or yes needed mods and the whitelisted pnes, cause one per one it gonna be a bit uff

**Comment by Mrgaton** [comment]
I guess that it shows on console so I can copy and paste

**Comment by DiffuseHyperion** [comment]
Sorry about the delay, just released [version 0.0.7](https://github.com/DiffuseHyperion/InertiaAntiCheat/releases/tag/0.0.7) that should fix this. Try downloading [InertiaAntiCheat-0.0.7+1.20.1.jar](https://github.com/DiffuseHyperion/InertiaAntiCheat/releases/download/0.0.7/InertiaAntiCheat-0.0.7+1.20.1.jar) and see if that works.
