### ISSUE TITLE
BUG: Log says I require fabric 0.102.0

### ISSUE THREAD

**Issue by Misha4ek** [DiffuseHyperion/InertiaAntiCheat#49]
Log says I require fabric 0.102.0
Mod for 1.21.1
Fabric 0.16.5

[23:46:53] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.5
[23:46:53] [main/WARN]: Mod resolution failed
[23:46:53] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE inertiaanticheat 1.0.3.1 {depends fabric @ [>=0.102.0+1.21.1]}, ROOT_FORCELOAD_SINGLE inertiaanticheat 1.0.3.1]
[23:46:53] [main/INFO]: Reason: [HARD_DEP inertiaanticheat 1.0.3.1 {depends fabric @ [>=0.102.0+1.21.1]}]
[23:46:53] [main/INFO]: Fix: add [add:fabric 0.102.0+1.21.1 ([[0.102.0+1.21.1,∞)])], remove [], replace []
[23:46:53] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric, version 0.102.0+1.21.1 or later.
More details:
	 - Mod 'InertiaAntiCheat' (inertiaanticheat) 1.0.3.1 requires version 0.102.0+1.21.1 or later of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.5-launcher.1.0.1.jar:1.0.1]

**Comment by Misha4ek** [comment]
Log, tell me Fabric API please.
